# Generated by Django 2.2.14 on 2023-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20230524_2127"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="added_from_canal",
            field=models.BooleanField(default=False),
        ),
    ]
