# Generated by Django 2.2.14 on 2023-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_item_added_from_canal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="canal_variant_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=34, null=True, unique=True
            ),
        ),
    ]
