# Generated by Django 2.2.14 on 2023-05-30 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20230525_1753"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fulfillment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canal_id", models.CharField(blank=True, max_length=34, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "pending"),
                            ("O", "open"),
                            ("S", "success"),
                            ("C", "cancelled"),
                            ("E", "error"),
                            ("F", "failure"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "shipment_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "confirmed"),
                            ("in_transit", "in_transit"),
                            ("out_for_delivery", "out_for_delivery"),
                            ("delivered", "delivered"),
                            ("failure", "failure"),
                        ],
                        max_length=100,
                    ),
                ),
                ("service", models.CharField(max_length=100)),
                ("tracking_company", models.CharField(max_length=100)),
                ("tracking_number", models.CharField(max_length=100)),
                ("tracking_url", models.CharField(max_length=500)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FulfillmentLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "fulfillment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Fulfillment",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.OrderItem"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
