# Generated by Django 2.2.14 on 2023-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230530_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='shipment_status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('in_transit', 'in_transit'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered'), ('failure', 'failure')], max_length=100, null=True),
        ),
    ]
