# Generated by Django 2.2.14 on 2023-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230601_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='canal_variant_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
    ]
